[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "."

# --- Agent Scheduling & Configuration ---

[functions."architect-day-1-questions"]
  # Runs every Monday at 5:00 AM UTC
  schedule = "0 5 * * 1"
  background = true
  timeout = 900 # 15 minutes max
  included_files = ["assets/**"]

[functions."architect-day-2-seo"]
  # Runs every Tuesday at 5:00 AM UTC
  schedule = "0 5 * * 2"
  background = true
  timeout = 900
  included_files = ["assets/**"]

[functions."architect-day-3-tag-enrichment"]
  # Runs every Wednesday at 5:00 AM UTC
  schedule = "0 5 * * 3"
  background = true
  timeout = 900
  included_files = ["assets/**"]

[functions."architect-day-4-gap-analysis"]
  # Runs every Thursday at 5:00 AM UTC
  schedule = "0 5 * * 4"
  background = true
  timeout = 900
  included_files = ["assets/**"]

[functions."architect-day-5-maintenance"]
  # Runs every Friday at 5:00 AM UTC
  schedule = "0 5 * * 5"
  background = true
  timeout = 900
  included_files = ["assets/**"]

[functions."architect-day-6-simulation"]
  # Runs every Saturday at 5:00 AM UTC
  schedule = "0 5 * * 6"
  background = true
  timeout = 900
  included_files = ["assets/**"]

[functions."architect-day-7-strategy"]
  # Runs every Sunday at 5:00 AM UTC
  schedule = "0 5 * * 0"
  background = true
  timeout = 900
  included_files = ["assets/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Content Security Policy (CSP) Headers
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdn.tailwindcss.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://rsms.me; font-src 'self' https://fonts.gstatic.com https://rsms.me; img-src 'self' https: data:;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
